[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
optimizer = true
optimizer_runs = 15
via_ir = true
extra_output_files = ['abi']
fs_permissions = [
  { access = "read", path = "./script/res" },
  { access = "read", path = "./test/res" },
]

[rpc_endpoints]
ethereum = { endpoint = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}", retries = 10, retry_backoff = 3000, compute_units_per_second = 100 }
base = { endpoint = "https://base-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}", retries = 10, retry_backoff = 3000, compute_units_per_second = 100 }
sepolia = { endpoint = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}", retries = 10, retry_backoff = 3000, compute_units_per_second = 100 }
base_sepolia = { endpoint = "https://base-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}", retries = 10, retry_backoff = 3000, compute_units_per_second = 100 }

[profile.ci]
# inherits [profile.default]

[fmt]
sort_imports = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
