name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Build
        run: forge build --use solc:0.8.28 --via-ir --optimize --optimizer-runs 15 --sizes

      - name: Unit tests
        run: forge test --use solc:0.8.28 --via-ir --optimize --optimizer-runs 15 -vvv --nmc '(ForkTest|AdhocTest)'

  fork:
    name: Fork tests
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        run: forge --version

      - name: Build
        run: forge build --use solc:0.8.28 --via-ir --optimize --optimizer-runs 15 --sizes

      - name: Fork tests
        env:
          ALCHEMY_API_KEY:  "${{ secrets.ALCHEMY_API_KEY }}"
        # `--threads` and `--cups` are used to avoid getting rate limited
        run: forge test --use solc:0.8.28 --via-ir --optimize --optimizer-runs 15 -vvv --threads 1 --cups 5 --mc ForkTest --nmc AdhocTest
